import turtle

"""Swastika symbol Hindu auspicious sign defamed by Germans, don't get alarmed by it 
as in India this is everywhere since 5000+ BC"""

slowpoke = turtle.Turtle()
slowpoke.shape('turtle')
slowpoke.pensize(15)
slowpoke.pencolor('red')
slowpoke.backward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.penup()
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.pendown()
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.penup()
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.pendown()
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.forward(100)
slowpoke.right(90)
slowpoke.penup()
slowpoke.forward(50)
slowpoke.right(90)
slowpoke.forward(50)

slowpoke.pendown()
slowpoke.circle(5)
slowpoke.penup()
slowpoke.forward(100)
slowpoke.pendown()
slowpoke.circle(5)
slowpoke.penup()

slowpoke.left(90)
slowpoke.penup()
slowpoke.forward(100)
slowpoke.pendown()
slowpoke.circle(5)
slowpoke.penup()

slowpoke.left(90)
slowpoke.penup()
slowpoke.forward(100)
slowpoke.pendown()
slowpoke.circle(5)
slowpoke.penup()

slowpoke.goto(100, 100)

turtle.mainloop()
